from typing import List, TypedDict, Optional

class ResearchState(TypedDict):
    """
    Represents the state of our research agent.
    This TypedDict is used to pass data between nodes in the graph.
    """
    user_query: str               # The original query from the user
    search_queries: List[str]     # List of search queries generated by the AI
    search_results: List[dict]    # List of search results from the web
    critique: str                 # Critique and reflection on the search results
    report: str                   # The final, synthesized report
    is_complete: bool             # Flag to indicate if the research is complete
    cycle_count: int              # Counter for the number of research cycles 